#!/usr/bin/env python3
"""
PowerFix backend — runs the real research + math + PDF pipeline.

Deployed on Render. The GitHub Pages frontend (index.html) POSTs here
instead of calling Claude directly, so the resulting PDF is generated by
the actual locked powerfix_engine.py / powerfix_render.py renderer —
the same one used for the RD and Guatemala case studies.

Endpoint:
  POST /api/generate  { territory, caseNum (optional), apiKey }
  -> { research: {...}, math: {...}, caseNum, pdf_base64: "..." }
"""

import os
import sys
import base64
import dataclasses

from flask import Flask, request, jsonify
from flask_cors import CORS

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from auto_case import research_territory, build_case_inputs, next_case_number, try_download_photos
from powerfix_engine import compute
from powerfix_render import render

app = Flask(__name__)
CORS(app)


@app.route("/health")
def health():
    return jsonify({"ok": True})


@app.route("/api/generate", methods=["POST"])
def generate():
    body = request.get_json(force=True, silent=True) or {}
    territory = (body.get("territory") or "").strip()
    api_key = (body.get("apiKey") or "").strip()
    case_num = body.get("caseNum")

    if not territory:
        return jsonify({"error": "missing territory"}), 400
    if not api_key.startswith("sk-"):
        return jsonify({"error": "invalid API key"}), 400

    try:
        research = research_territory(territory, api_key=api_key)
        case_number = int(case_num) if case_num else next_case_number()
        inp = build_case_inputs(research, case_number)

        tmp_photo_dir = os.path.join(HERE, "output", "_tmp_photos")
        inp.photos = try_download_photos(research, tmp_photo_dir)

        res = compute(inp)

        out_dir = os.path.join(HERE, "output")
        os.makedirs(out_dir, exist_ok=True)
        safe_name = territory.replace(" ", "_")
        out_path = os.path.join(out_dir, f"PowerFix_CaseStudy{case_number}_{safe_name}.pdf")
        render(inp, res, out_path)

        with open(out_path, "rb") as f:
            pdf_b64 = base64.b64encode(f.read()).decode("ascii")

        return jsonify({
            "research": research,
            "math": dataclasses.asdict(res),
            "caseNum": case_number,
            "filename": os.path.basename(out_path),
            "pdf_base64": pdf_b64,
        })

    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5050))
    app.run(host="0.0.0.0", port=port)
